config/routes.rb
Rails.application.routes.draw do
  
  

  root 'travellers#index'
  resources :travellers

end

app/models/traveller.rb
class Traveller < ActiveRecord::Base
	validates_presence_of :city
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/travellers_controller.rb
class TravellersController < ApplicationController
	
	before_action :set_traveller, :only =>[ :show, :update, :destroy]
	def index
  		#@travellers = Traveller.page(params[:page]).per(5)
  		#如果要做 id 遞降
  		@travellers = Traveller.order("id DESC").page(params[:page]).per(5)
		
  		if params[:traveller_id]
  			@traveller = Traveller.find( params[:traveller_id] )
  		else
			@traveller = Traveller.new
  		end

  		respond_to do |format|
    		format.html # index.html.erb
    		format.xml { render :xml => @events.to_xml }
    		format.json { render :json => @events.to_json }
    		format.atom { @feed_title = "My event list" } # index.atom.builder
  		end

	end


	

	def create
  		@traveller = Traveller.new(traveller_params)
  		if @traveller.save
			redirect_to travellers_path
      		flash[:notice] = "新增成功的訊息"
    	else
      		@travellers = Traveller.order("id DESC").page(params[:page]).per(5)
      		flash[:alert] = "新增失敗的訊息"
      		render "index"
		end
	end

	def show
		
		respond_to do |format| 
			format.html { @page_title = @traveller.city } # show.html.erb 
			format.xml # show.xml.builder 
			format.json { render :json => { id: @traveller.id, city: @traveller.city }.to_json } 
		end

	end



	def update
		

		if @traveller.update(traveller_params)

      		redirect_to travellers_path
      		flash[:notice] = "event was successfully updated"
    	else
      		@travellers = Traveller.order("id DESC").page(params[:page]).per(5)
      		render "index"
    	end
	end

	def destroy
  		
  		@traveller.destroy

  		redirect_to :back
  		flash[:alert] = "successfully deleted"
	end



	private
	def set_traveller
		@traveller = Traveller.find(params[:id])
	end



	def traveller_params
  		params.require(:traveller).permit(:city, :date, :note)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/travellers_helper.rb
module TravellersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniTraveller</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
	<div class="row">
	<div class="col-md-12">
		<% if flash[:notice].present? %>
			<div class="alert alert-success" role="alert">
				<%= flash[:notice] %>
			</div>
		<% end %>

		<% if flash[:alert].present? %>
			<div class="alert alert-danger" role="alert">
				<%= flash[:alert] %>
			</div>
		<% end %>


		<%= yield %>
	</div>

	</div>

</div>


</body>
</html>

app/views/travellers/_form.html.erb
	<div class="form-group">
 	   	<%= f.label :city, "City" %>
    	<%= f.text_field :city, :class => "form-control" %>
    </div>
	
	<div class="form-group">
    	
    	<%= f.label :date, "Date" %></li>

    	<%= f.text_field :date, :class => "form-control"  %></li>
    	
	</div>
	<div class="form-group">
    	<%= f.label :note, "Note" %>
    	<%= f.text_area :note, :class => "form-control" %>
	</div>

app/views/travellers/edit.html.erb
<%= form_for @traveller, :url => traveller_path(@traveller), :method => :patch do |f| %>
    
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update",:class => "btn btn-primary" %>
<% end %>

app/views/travellers/index.html.erb
<h1>TRIP DIARY</h1>
<table>
	<tr>
		<td><%= "City" %></td>
    	<td><%= "Date" %></td>
    	
    	
	</tr>
<% @travellers.each do |t| %>
	
 	<tr>
    	<td>
    	<%= t.city %>
    	</td>
    	<td>
    	<%= t.date %>
    	</td>
    	
		<td>    
    	<%= link_to "Show", traveller_path(t), :class => "btn btn-primary" %>
    	<%= link_to 'Edit', travellers_path(:traveller_id => t), :class => "btn btn-default" %>
    	<%= link_to 'Delete', traveller_path(t), :method => :delete, :data =>{:confirm =>"R U SURE???"}, :class => "btn btn-danger" %>
    	</td>
  	</tr>
<% end %>
</table>

<hr>
  <%= link_to 'New Page', travellers_path, :class => "btn btn-default" %>

<%= paginate @travellers %>

<%
  if params[:traveller_id]
    url = traveller_path(@traveller)
  else
    url = travellers_path
  end
%>


<%= form_for @traveller, :url => url do |f| %>
    
	<% if @traveller.errors.any? %>
      <ul>
          <% @traveller.errors.full_messages.each do |m| %>
            <li><%= m %></li>
        <% end %>
      </ul>
  <% end %>

	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Submit",:class => "btn btn-primary" %>
<% end %>

app/views/travellers/new.html.erb
<%= form_for @traveller, :url => travellers_path do |f| %>
    
	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create",:class => "btn btn-primary" %>
<% end %>

app/views/travellers/show.html.erb
<p>city: <%= @traveller.city %></p>
<p>date: <%= @traveller.date %></p>
<p>note: <%= @traveller.note %></p>

<p>
	<%= link_to "back to index", travellers_path%>
</p>